### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zoudf** [cmars/pystdf#15]
OS: ubuntu server 16.04
python: 2.7.12
install log:

azou@UbuntuTest:~/ink/pystdf-master$ sudo python setup.py install
[sudo] password for azou:
running install
running build
running build_py
running build_scripts
running install_lib
byte-compiling /usr/local/lib/python2.7/dist-packages/pystdf/V4.py to V4.pyc
  File "/usr/local/lib/python2.7/dist-packages/pystdf/V4.py", line 169
    class Atr(RecordType, metaclass=StdfRecordMeta):
                                   ^
SyntaxError: invalid syntax

running install_scripts
changing mode of /usr/local/bin/stdf2excel to 755
changing mode of /usr/local/bin/stdf_slice to 755
changing mode of /usr/local/bin/rec_index to 755
changing mode of /usr/local/bin/stdf2xml to 755
changing mode of /usr/local/bin/stdf2text to 755
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/pystdf-1.3.2.egg-info
Writing /usr/local/lib/python2.7/dist-packages/pystdf-1.3.2.egg-info

**Comment by cmars** [comment]
Sorry, only python 3 is supported.
