### ISSUE TITLE
Some tests are showing incomplete PTR records 

### ISSUE THREAD

**Issue by xdonu2x** [cmars/pystdf#51]
Thank you for such an awesome tool. 

I just started using the tool, and I encountered this issue. For some of the tests the PTR is incomplete. I get RESULTS but no other information like : 

OPT_FLAG
RES_SCAL
LLM_SCAL
HLM_SCAL
LO_LIMIT
HI_LIMIT
UNITS
C_RESFMT
C_LLMFMT
C_HLMFMT
LO_SPEC
HI_SPEC

[sample1.csv](https://github.com/cmars/pystdf/files/13257507/sample1.csv)

**Comment by cmars** [comment]
Check the REC_LEN in your STDF file. Your record might be ending early and missing these fields. If not, please reopen with an example attached and I'll try to turn it into a test case.

**Comment by xdonu2x** [comment]
Hi Casey,

Thanks for responding. I have figured it out. I missed the fact that only
the first occurrence of the tests sets the semi-static information.

However, I would really appreciate it if you can point me to more
documentation as to how to use this package. I must admit I am not
proficient in python yet (still learning) specially object oriented
programming.
It you can point me in the right direction of how to use the Parametric
Summarizer, Part Summarizer, Bin Summarizer classes it would be really be
helpful.

Thanks again for your help.

Don
