### ISSUE TITLE
Can't install package from PyPi

### ISSUE THREAD

**Issue by vbukhonov** [cmars/pystdf#7]
Hello!

I've been working with you library for a few, but now I am struggling from the following problem: on PyPi there is only link to 1.0.0 version - [pystdf 1.0.0](https://pypi.python.org/pypi/pystdf/), while there is a version 1.3.1 according to [Google repo](https://code.google.com/archive/p/pystdf/downloads), from which the project migrated here, on github. Could you, please, update info on PyPi and link the current version to it?
Thank you!

**Comment by sschaetz** [comment]
We are also interested in pulling latest pystdf from pypi. @cmars any plans on pushing the latest version?
